export interface Imovel {
  _id:             string,
  cidade:         string,
  estado:         string,
  banco:          string,
  numero_imovel:   string,
  imagem:         string,
  link:           string,
  valor_avaliacao: number,
  tipoImovel:     string,
  endereco:       string,
  datas_leiloes: Date[], 
  valor_minimo_1_leilao: number | null, 
  valor_minimo_2_leilao: number | null,
  formas_pagamento: string[],
}
